const $=id=>document.getElementById(id),labels=['正常','爆裂音','哮鸣音','混合异常音'];
const presets=[[.86,.06,.05,.03],[.09,.76,.05,.10],[.08,.04,.79,.09],[.07,.14,.17,.62]];
let ctx,buffer,url,sample=null,busy=false,loadVersion=0;
function context(){return ctx??=new (window.AudioContext||window.webkitAudioContext)()}
function resetResult(){ $('prediction').textContent='等待分析';$('prediction-note').textContent='分类分数为预设演示数据。';renderBars(null)}
function renderBars(values){$('bars').innerHTML=labels.map((label,i)=>`<div class="${values&&i===values.indexOf(Math.max(...values))?'winner':''}"><div class="bar-label"><span>${label}</span><span>${values?(values[i]*100).toFixed(1)+'%':'—'}</span></div><div class="track"><div class="fill" style="width:${values?values[i]*100:0}%"></div></div></div>`).join('')}
function plot(){let data=buffer.getChannelData(0),c=$('wave'),g=c.getContext('2d'),w=c.width,h=c.height;g.clearRect(0,0,w,h);g.strokeStyle='#e0e9df';for(let y=30;y<h;y+=30){g.beginPath();g.moveTo(0,y);g.lineTo(w,y);g.stroke()}g.strokeStyle='#25866c';g.beginPath();for(let x=0;x<w;x++){let a=Math.floor(x*data.length/w),b=Math.max(a+1,Math.floor((x+1)*data.length/w)),lo=1,hi=-1;for(let j=a;j<b;j++){lo=Math.min(lo,data[j]);hi=Math.max(hi,data[j])}g.moveTo(x,h/2-lo*h*.44);g.lineTo(x,h/2-hi*h*.44)}g.stroke();spectrum(data,buffer.sampleRate);$('duration').textContent=buffer.duration.toFixed(2)+' s'}
function fft(re,im){const n=re.length;for(let i=1,j=0;i<n;i++){let bit=n>>1;for(;j&bit;bit>>=1)j^=bit;j^=bit;if(i<j){[re[i],re[j]]=[re[j],re[i]]}}for(let len=2;len<=n;len<<=1){let angle=-2*Math.PI/len;for(let start=0;start<n;start+=len){for(let j=0;j<len/2;j++){let co=Math.cos(angle*j),si=Math.sin(angle*j),k=start+j,l=k+len/2,tr=re[l]*co-im[l]*si,ti=re[l]*si+im[l]*co;re[l]=re[k]-tr;im[l]=im[k]-ti;re[k]+=tr;im[k]+=ti}}}}
function spectrum(data,sr){let c=$('spectrum'),g=c.getContext('2d'),w=450,h=120,img=g.createImageData(w,h),n=1024,maxFreq=Math.min(4000,sr/2);for(let x=0;x<w;x++){let start=Math.floor(x*Math.max(0,data.length-n)/(w-1)),re=new Float64Array(n),im=new Float64Array(n);for(let i=0;i<n;i++)re[i]=(data[start+i]||0)*(.5-.5*Math.cos(2*Math.PI*i/(n-1)));fft(re,im);for(let y=0;y<h;y++){let k=Math.round((h-1-y)/(h-1)*maxFreq/sr*n),mag=Math.hypot(re[k],im[k])/n,db=20*Math.log10(mag+1e-8),v=Math.max(0,Math.min(1,(db+90)/65)),stops=[[13,41,40],[39,126,113],[155,189,112],[239,211,151]],z=v*3,a=Math.min(2,Math.floor(z)),t=z-a,p=(y*w+x)*4;for(let q=0;q<3;q++)img.data[p+q]=stops[a][q]*(1-t)+stops[a+1][q]*t;img.data[p+3]=255}}let off=document.createElement('canvas');off.width=w;off.height=h;off.getContext('2d').putImageData(img,0,0);g.drawImage(off,0,0,c.width,c.height)}
function wav(b){let samples=b.getChannelData(0),a=new ArrayBuffer(44+samples.length*2),v=new DataView(a);const str=(o,s)=>{for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i))};str(0,'RIFF');v.setUint32(4,a.byteLength-8,true);str(8,'WAVE');str(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,b.sampleRate,true);v.setUint32(28,b.sampleRate*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);str(36,'data');v.setUint32(40,samples.length*2,true);samples.forEach((s,i)=>v.setInt16(44+i*2,Math.max(-1,Math.min(1,s))*32767,true));return new Blob([a],{type:'audio/wav'})}
function install(b,name,blob,kind){buffer=b;sample=kind;if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(blob);$('player').src=url;$('filename').textContent=name;$('metadata').textContent=`${b.duration.toFixed(1)} s · ${(b.sampleRate/1000).toFixed(1)} kHz`;$('signal-badge').textContent='真实信号可视化';$('analyze').disabled=false;$('status').textContent=kind===null?'已加载音频；分类将展示固定示例结果。':'已加载合成示例；分类将展示对应预设结果。';document.querySelectorAll('[data-sample]').forEach(e=>e.classList.toggle('selected',Number(e.dataset.sample)===kind));resetResult();plot()}
function synth(kind){loadVersion++;if(busy)return;let b=context().createBuffer(1,16000*6,16000),d=b.getChannelData(0),seed=42;const random=()=>{seed=(1664525*seed+1013904223)>>>0;return seed/4294967296-.5};let noise=0;for(let i=0;i<d.length;i++){let t=i/16000,env=Math.pow(Math.sin(Math.PI*(t%3)/3),2);noise=.88*noise+.12*random();let s=noise*.7*env;if(kind===2||kind===3)s+=.13*env*Math.sin(2*Math.PI*(620*t+12*Math.sin(t*2)));if(kind===1||kind===3){for(let p of [1.1,1.43,2.05,4.2,4.65]){let dt=t-p;if(dt>0&&dt<.035)s+=.4*Math.exp(-dt*120)*random()}}d[i]=s}install(b,`合成示例 · ${labels[kind]}.wav`,wav(b),kind)}
async function upload(file){if(!file||busy)return;const version=++loadVersion;$('analyze').disabled=true;$('status').textContent='正在读取音频…';try{if(file.size>30*1024*1024)throw Error('音频超过 30 MB，请选择更小的文件。');let b=await context().decodeAudioData(await file.arrayBuffer());if(version!==loadVersion)return;install(b,file.name,file,null)}catch(e){if(version!==loadVersion)return;$('status').textContent=e.message.includes('30 MB')?e.message:'无法解码此音频，请尝试 WAV 或 MP3 文件。';$('analyze').disabled=!buffer}}
$('file').addEventListener('change',e=>upload(e.target.files[0]));document.querySelectorAll('[data-sample]').forEach(e=>e.onclick=()=>synth(Number(e.dataset.sample)));for(let event of ['dragenter','dragover'])$('drop').addEventListener(event,e=>{e.preventDefault();$('drop').classList.add('drag')});for(let event of ['dragleave','drop'])$('drop').addEventListener(event,e=>{e.preventDefault();$('drop').classList.remove('drag')});$('drop').addEventListener('drop',e=>upload(e.dataTransfer.files[0]));$('analyze').onclick=async()=>{if(!buffer||busy)return;busy=true;$('analyze').disabled=true;$('status').textContent='正在展示分类流程…';await new Promise(r=>setTimeout(r,650));let kind=sample??3;renderBars(presets[kind]);$('prediction').textContent=labels[kind];$('prediction-note').textContent=sample===null?'上传音频：固定混合类示例，与音频内容无关。':'合成示例：展示对应类别的预设分数。';$('status').textContent=`${$('model').value} · 演示完成，未执行模型推理。`;busy=false;$('analyze').disabled=false};resetResult();
